version: 0.2

env:
    variables:
        S3_BUCKET: "front-end-2018-karthik"
        #APP_NAME: "<APP_NAME_HERE>"
        BUILD_ENV : "prod"

phases:
    install:
        commands:
        # Download and Install NodeJS 8.0     
        - sudo apt-get update -y
        - sudo apt-get install -y nodejs
        - echo Installing source NPM dependencies...
        # Install http drivers for node
        - sudo apt-get update -y
        # Install Node Package Manager (Replace the commands below if you using NPM).
        - sudo apt-get install npm -y
        - sudo apt-get update -y
        # Verify Node npm installation 
        - npm --version
        - nodejs --version
        # set npm registry to http
        - npm config set registry="http://registry.npmjs.org/"
        # Install Angular CLI, If you are not using Angular 6, install angular/cli@1.7.0 or lower, confirm by running ng -v inside your project folder
        - npm install @angular/cli -y
        # Install node dependancies.
        - ng --version
        - npm install

    build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build started on `date`
        - ng build

    post_build:
        commands:
        # Clear S3 bucket.
        - aws s3 rm s3://${S3_BUCKET} --recursive
        - echo S3 bucket is cleared.
        # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
        - aws s3 cp dist s3://${S3_BUCKET} --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'